### ISSUE TITLE
TODO: guild loading

### ISSUE THREAD

**Issue by TinyPandas** [TinyPandas/TheGiver#2]
- [x] Remove guild pre-loading
- [x] Attempt to bind roles on initial slash-command interaction | or on guild-join
- [ ] ~~Retroactively bind roles on startup, if not set~~
- [x] Implement setroles message-based command for anyone with `MANAGE_SERVER` && `MANAGE_ROLES`
